// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"
	tmdb2 "github.com/clambin/tmdb/pkg/tmdb"

	mock "github.com/stretchr/testify/mock"
)

// TMDBClient is an autogenerated mock type for the TMDBClient type
type TMDBClient struct {
	mock.Mock
}

type TMDBClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TMDBClient) EXPECT() *TMDBClient_Expecter {
	return &TMDBClient_Expecter{mock: &_m.Mock}
}

// GetMovie provides a mock function with given fields: ctx, id
func (_m *TMDBClient) GetMovie(ctx context.Context, id int) (tmdb2.Movie, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMovie")
	}

	var r0 tmdb2.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (tmdb2.Movie, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) tmdb2.Movie); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(tmdb2.Movie)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TMDBClient_GetMovie_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovie'
type TMDBClient_GetMovie_Call struct {
	*mock.Call
}

// GetMovie is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TMDBClient_Expecter) GetMovie(ctx interface{}, id interface{}) *TMDBClient_GetMovie_Call {
	return &TMDBClient_GetMovie_Call{Call: _e.mock.On("GetMovie", ctx, id)}
}

func (_c *TMDBClient_GetMovie_Call) Run(run func(ctx context.Context, id int)) *TMDBClient_GetMovie_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *TMDBClient_GetMovie_Call) Return(_a0 tmdb2.Movie, _a1 error) *TMDBClient_GetMovie_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TMDBClient_GetMovie_Call) RunAndReturn(run func(context.Context, int) (tmdb2.Movie, error)) *TMDBClient_GetMovie_Call {
	_c.Call.Return(run)
	return _c
}

// GetMovieCredits provides a mock function with given fields: ctx, id
func (_m *TMDBClient) GetMovieCredits(ctx context.Context, id int) (tmdb2.MovieCredits, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMovieCredits")
	}

	var r0 tmdb2.MovieCredits
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (tmdb2.MovieCredits, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) tmdb2.MovieCredits); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(tmdb2.MovieCredits)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TMDBClient_GetMovieCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMovieCredits'
type TMDBClient_GetMovieCredits_Call struct {
	*mock.Call
}

// GetMovieCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TMDBClient_Expecter) GetMovieCredits(ctx interface{}, id interface{}) *TMDBClient_GetMovieCredits_Call {
	return &TMDBClient_GetMovieCredits_Call{Call: _e.mock.On("GetMovieCredits", ctx, id)}
}

func (_c *TMDBClient_GetMovieCredits_Call) Run(run func(ctx context.Context, id int)) *TMDBClient_GetMovieCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *TMDBClient_GetMovieCredits_Call) Return(_a0 tmdb2.MovieCredits, _a1 error) *TMDBClient_GetMovieCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TMDBClient_GetMovieCredits_Call) RunAndReturn(run func(context.Context, int) (tmdb2.MovieCredits, error)) *TMDBClient_GetMovieCredits_Call {
	_c.Call.Return(run)
	return _c
}

// GetPerson provides a mock function with given fields: ctx, id
func (_m *TMDBClient) GetPerson(ctx context.Context, id int) (tmdb2.Person, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPerson")
	}

	var r0 tmdb2.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (tmdb2.Person, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) tmdb2.Person); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(tmdb2.Person)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TMDBClient_GetPerson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPerson'
type TMDBClient_GetPerson_Call struct {
	*mock.Call
}

// GetPerson is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TMDBClient_Expecter) GetPerson(ctx interface{}, id interface{}) *TMDBClient_GetPerson_Call {
	return &TMDBClient_GetPerson_Call{Call: _e.mock.On("GetPerson", ctx, id)}
}

func (_c *TMDBClient_GetPerson_Call) Run(run func(ctx context.Context, id int)) *TMDBClient_GetPerson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *TMDBClient_GetPerson_Call) Return(_a0 tmdb2.Person, _a1 error) *TMDBClient_GetPerson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TMDBClient_GetPerson_Call) RunAndReturn(run func(context.Context, int) (tmdb2.Person, error)) *TMDBClient_GetPerson_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonCredits provides a mock function with given fields: ctx, id
func (_m *TMDBClient) GetPersonCredits(ctx context.Context, id int) (tmdb2.PersonCredits, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonCredits")
	}

	var r0 tmdb2.PersonCredits
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (tmdb2.PersonCredits, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) tmdb2.PersonCredits); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(tmdb2.PersonCredits)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TMDBClient_GetPersonCredits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonCredits'
type TMDBClient_GetPersonCredits_Call struct {
	*mock.Call
}

// GetPersonCredits is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TMDBClient_Expecter) GetPersonCredits(ctx interface{}, id interface{}) *TMDBClient_GetPersonCredits_Call {
	return &TMDBClient_GetPersonCredits_Call{Call: _e.mock.On("GetPersonCredits", ctx, id)}
}

func (_c *TMDBClient_GetPersonCredits_Call) Run(run func(ctx context.Context, id int)) *TMDBClient_GetPersonCredits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *TMDBClient_GetPersonCredits_Call) Return(_a0 tmdb2.PersonCredits, _a1 error) *TMDBClient_GetPersonCredits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TMDBClient_GetPersonCredits_Call) RunAndReturn(run func(context.Context, int) (tmdb2.PersonCredits, error)) *TMDBClient_GetPersonCredits_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPersonPage provides a mock function with given fields: ctx, query, page
func (_m *TMDBClient) SearchPersonPage(ctx context.Context, query string, page int) ([]tmdb2.Person, int, error) {
	ret := _m.Called(ctx, query, page)

	if len(ret) == 0 {
		panic("no return value specified for SearchPersonPage")
	}

	var r0 []tmdb2.Person
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]tmdb2.Person, int, error)); ok {
		return rf(ctx, query, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []tmdb2.Person); ok {
		r0 = rf(ctx, query, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tmdb2.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) int); ok {
		r1 = rf(ctx, query, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int) error); ok {
		r2 = rf(ctx, query, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TMDBClient_SearchPersonPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPersonPage'
type TMDBClient_SearchPersonPage_Call struct {
	*mock.Call
}

// SearchPersonPage is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - page int
func (_e *TMDBClient_Expecter) SearchPersonPage(ctx interface{}, query interface{}, page interface{}) *TMDBClient_SearchPersonPage_Call {
	return &TMDBClient_SearchPersonPage_Call{Call: _e.mock.On("SearchPersonPage", ctx, query, page)}
}

func (_c *TMDBClient_SearchPersonPage_Call) Run(run func(ctx context.Context, query string, page int)) *TMDBClient_SearchPersonPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *TMDBClient_SearchPersonPage_Call) Return(_a0 []tmdb2.Person, _a1 int, _a2 error) *TMDBClient_SearchPersonPage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TMDBClient_SearchPersonPage_Call) RunAndReturn(run func(context.Context, string, int) ([]tmdb2.Person, int, error)) *TMDBClient_SearchPersonPage_Call {
	_c.Call.Return(run)
	return _c
}

// NewTMDBClient creates a new instance of TMDBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTMDBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TMDBClient {
	mock := &TMDBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
