name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      target: tmdb-proxy
  release:
    needs:
      - build
    uses: clambin/workflows/.github/workflows/release.yaml@main

