name: push
on:
  push:
    branches-ignore:
      - main
      - bld
  pull_request_target:
permissions:
  contents: read
jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
