name: push

on:
  push:
    branches-ignore:
      - main
      - fix-memleak
  pull_request_target:

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
